
# Ejercicio final: Extraer información de un archivo JSON usando expresiones regulares (regex)


## Objetivo:

El objetivo de este ejercicio es practicar la utilización de expresiones regulares (regex) para extraer información específica de un archivo JSON. El ejercicio se enfocará en la lectura y análisis de un archivo JSON que contiene información sobre clientes.

## Descripción:

### Obtener el archivo JSON:
Lea archivo JSON 'clientes.json' que contiene la información sobre clientes. El archivo debe tener una estructura similar a la siguiente:

In [1]:
{
  "clientes": [
    {
      "nombre": "Juan Pérez",
      "direccion": "Calle Mayor 123",
      "ciudad": "San José",
      "telefono": "+506 2222-3333"
    },
    {
      "nombre": "María Gómez",
      "direccion": "Avenida Central 456",
      "ciudad": "Alajuela",
      "telefono": "+506 8888-4444"
    },
    {
      "nombre": "Pedro Ramírez",
      "direccion": "Barrio Escalante 789",
      "ciudad": "Heredia",
      "telefono": "+506 5555-6666"
    },
    {
      "nombre": "Ana Castro",
      "direccion": "Avenida 10 Calle 5",
      "ciudad": "Cartago",
      "telefono": "+506 3333-4444"
    },
    {
      "nombre": "Carlos Jiménez",
      "direccion": "Calle Principal 12",
      "ciudad": "Liberia",
      "telefono": "+506 6666-7777"
    },
    {
      "nombre": "Diana Solano",
      "direccion": "Barrio La Unión 78",
      "ciudad": "Puntarenas",
      "telefono": "+506 9999-8888"
    }
  ]
}

{'clientes': [{'nombre': 'Juan Pérez',
   'direccion': 'Calle Mayor 123',
   'ciudad': 'San José',
   'telefono': '+506 2222-3333'},
  {'nombre': 'María Gómez',
   'direccion': 'Avenida Central 456',
   'ciudad': 'Alajuela',
   'telefono': '+506 8888-4444'},
  {'nombre': 'Pedro Ramírez',
   'direccion': 'Barrio Escalante 789',
   'ciudad': 'Heredia',
   'telefono': '+506 5555-6666'},
  {'nombre': 'Ana Castro',
   'direccion': 'Avenida 10 Calle 5',
   'ciudad': 'Cartago',
   'telefono': '+506 3333-4444'},
  {'nombre': 'Carlos Jiménez',
   'direccion': 'Calle Principal 12',
   'ciudad': 'Liberia',
   'telefono': '+506 6666-7777'},
  {'nombre': 'Diana Solano',
   'direccion': 'Barrio La Unión 78',
   'ciudad': 'Puntarenas',
   'telefono': '+506 9999-8888'}]}

##

## Extraer información usando regex:
### Utilice expresiones regulares para extraer la siguiente información de cada cliente:
- Nombre completo: Juan Pérez, María Gómez, Pedro Ramírez
- Dirección completa: Calle Mayor 123, Avenida Central 456, Barrio Escalante 789
- Ciudad: San José, Alajuela, Heredia
- Número de teléfono: +506 2222-3333, +506 8888-4444, +506 5555-6666

### Imprima la información extraída para cada cliente en un formato claro y organizado.


## Pistas:

- Utilice la librería re de Python para trabajar con expresiones regulares.
- Defina patrones de expresión regular específicos para cada tipo de información que desea extraer.
- Recorra el archivo JSON y aplique los patrones regex a cada cliente.
- Utilize métodos como findall() o search() para encontrar las coincidencias en el texto.

In [40]:
import json
import re

# Cargar el archivo JSON
try:
    with open("clientes.json", "r", encoding="utf-8") as archivo:
        datos_clientes = json.load(archivo)
except FileNotFoundError as e:
    print(f"Error: El archivo JSON 'clientes.json' no se encontró.")
except json.JSONDecodeError as e:
    print(f"Error al decodificar el archivo JSON: {e}")
except Exception as e:
    print(f"Error inesperado: {e}")

# Definir patrones de regex

print(datos_clientes)

{'clientes': [{'nombre': 'Juan Pérez', 'direccion': 'Calle Mayor 123', 'ciudad': 'San José', 'telefono': '+506 2222-3333'}, {'nombre': 'María Gómez', 'direccion': 'Avenida Central 456', 'ciudad': 'Alajuela', 'telefono': '+506 8888-4444'}, {'nombre': 'Pedro Ramírez', 'direccion': 'Barrio Escalante 789', 'ciudad': 'Heredia', 'telefono': '+506 5555-6666'}, {'nombre': 'Ana Castro', 'direccion': 'Avenida 10 Calle 5', 'ciudad': 'Cartago', 'telefono': '+506 3333-4444'}, {'nombre': 'Carlos Jiménez', 'direccion': 'Calle Principal 12', 'ciudad': 'Liberia', 'telefono': '+506 6666-7777'}, {'nombre': 'Diana Solano', 'direccion': 'Barrio La Unión 78', 'ciudad': 'Puntarenas', 'telefono': '+506 9999-8888'}]}


In [64]:
import re

patron_cliente = r"""
    nombre:\s+ 
    (?P<nombre>[\w\s]+),\s+ 
    direccion:\s+ 
    (?P<direccion>[\w\s,]+),\s+ 
    ciudad:\s+ 
    (?P<ciudad>[\w\s]+),\s+ 
    telefono:\s+ 
    (?P<telefono>[\+\d\s-]+) 
"""

clientes = datos_clientes['clientes']

patron_compilado = re.compile(patron_cliente, flags=re.VERBOSE)

# Iteramos sobre la lista de clientes
for cliente in clientes:
    # Concatenamos los valores del cliente en una cadena para aplicar la regex
    cliente_str = f"nombre: {cliente['nombre']}, direccion: {cliente['direccion']}, ciudad: {cliente['ciudad']}, telefono: {cliente['telefono']}"
    
    coincidencias = patron_compilado.findall(cliente_str)
    
    for coincidencia in coincidencias:
        nombre, direccion, ciudad, telefono = coincidencia
        print(f"Nombre: {nombre}\nDirección: {direccion}\nTeléfono: {telefono}\n")

Nombre: Juan Pérez
Dirección: Calle Mayor 123
Teléfono: +506 2222-3333

Nombre: María Gómez
Dirección: Avenida Central 456
Teléfono: +506 8888-4444

Nombre: Pedro Ramírez
Dirección: Barrio Escalante 789
Teléfono: +506 5555-6666

Nombre: Ana Castro
Dirección: Avenida 10 Calle 5
Teléfono: +506 3333-4444

Nombre: Carlos Jiménez
Dirección: Calle Principal 12
Teléfono: +506 6666-7777

Nombre: Diana Solano
Dirección: Barrio La Unión 78
Teléfono: +506 9999-8888

